name: Merge InterText Files On Push

on:
  push:
    branches: [ "main" ]

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install package
      run: |
        pip install git+https://github.com/OpenPecha/intertext-files-merger.git

    - name: Get Commit Message
      run: |
        commit_msg="${{ github.event.head_commit.message }}"
        
        python .github/script/intertext_merger.py "$commit_msg"
        
    - name: Commmit changes
      run: |
        sh git_config_account.sh
        git add data/output/*
        git commit -m "update output data"
  
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
